repos:
-   repo: https://github.com/python/black
    rev: 19.3b0
    hooks:
    -   id: black
        args: [--safe, --quiet]
        language_version: python3
-   repo: https://github.com/asottile/blacken-docs
    rev: v1.3.0
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==19.3b0]
        language_version: python3
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.8
    hooks:
    -   id: flake8
        additional_dependencies: [
                flake8-import-order,
                flake8-bandit,
                flake8-blind-except,
                flake8-bugbear,
                flake8-builtins,
                flake8-docstrings,
                flake8-logging-format,
                flake8-mypy,
                pep8-naming,
                pygments,
          ]
        language_version: python3
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: no-commit-to-branch
        args: [--branch, master]
        language_version: python3
    -   id: detect-private-key
    -   id: check-symlinks
    -   id: check-toml
    -   id: check-yaml

